#!/usr/bin/env perl

use strict;
use warnings;

use String::Cursor;

my ( $string );

$string = String::Cursor->new( data => join '', 'a' .. 'z' );

print $string->data, "\n";
$string->move( qr/b/ );
print $string->tail, "\n";
$string->move( qr/b/ );
print $string->tail, "\n";
$string->reset->move( qr/b/ );
print $string->tail, "\n";
$string->move( qr/../ );
print $string->tail, "\n";
$string->move( +3 );
print $string->tail, "\n";
