#!/usr/bin/env perl

use Modern::Perl;

my ( $data );

$data = "abcdefghi";

#warn $data =~ m/f/;
#warn "$-[0] $+[0]\n";

pos $data = 4;

scalar $data =~ m/\G./;
say pos $data;

say scalar $data =~ m/\G.*?(hi)/;
say "$-[1] $+[1]\n";
say pos $data;

#pos $data = 2;

#warn $data =~ m/\G(.)/;
#warn "$-[0] $+[0]\n";

say rindex 'abcd', 'd', 10;

